# Site settings

title: Civil Service LGBT Impact Index

description: "The Civil Service LGBT Impact Index celebrates the civil servants making things better for LGBT people."

baseurl: "/awards" # the subpath of your site, e.g. /blog
url: "//civilservice.lgbt"
author: "Civil Service Rainbow Alliance"
logo: "/logo.png"

asset-path: "/assets"
image-path: "/img"
image-2x-path: "/img/@2x"

# Timelines:
nominations: "open" # choose "open", "closed" or "ended"
nominations-open: "2017-04-24 00:00"
nominations-close: "2017-06-16 23:59"

shortlists: false # choose true or false
shortlist-starts: "2017-08-01 00:00"
shortlist-closes: "2017-09-01 23:59"

publish: false # choose true or false
publish-date: "2017-10-01 00:00" # date we publish the full index
awards-evening: "2017-10-01 00:00" # date we

# Social settings
facebook-id: "119705998363968" # For Facebook OpenGraph integration
facebook-slug: "ukcsra" # Automatically pre-pends http://facebook.com/
twitter-username: "ukcsra" # Twitter handle i.e. joebloggs
github-username:  "ukcsra"
google-site-verification: "RA-YBjxyRYVSuSFAYLKkufs6gjme6kMcihoB2KgKrTA" # GSV code; proves domain ownership

# Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-47423042-1" # GA ID code

# Collections
collections:
  indices:
    output: true
    permalink: /indices/:path/
    defaults:
      values:
        layout: page

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from